# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

# Docker Compose file for building and serving the OCUDU documentation site using Docusaurus.

# Before running, ensure that the OCUDU_GROUP_PATH environment variable is set to the path
# where the OCUDU repositories are located on your host machine.
# OCUDU_GROUP_PATH=/builds/ocudu docker compose up

services:
  docusaurus:
    image: node:22
    working_dir: /builds/ocudu/ocudu_docs
    volumes:
      - ./:/builds/ocudu/ocudu_docs
      # Static documentation from other OCUDU repositories
      - ${OCUDU_GROUP_PATH}/ocudu/build_doxygen/docs/doxygen/html:/builds/ocudu/ocudu_docs/static/doxygen:ro
    ports:
      - "3001:3000"
    stop_grace_period: 1s
    user: "1000:1000"
    command: >
      sh -c "
      echo '--- Starting Docusaurus server ---' &&
      npm install --no-audit --no-fund &&
      npm run clear &&
      npm run start -- --host 0.0.0.0 --poll 1000
      "
