#
# Copyright 2021-2026 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

services:
  docusaurus:
    image: node:20
    working_dir: /workdir/
    volumes:
      - ./:/workdir
    ports:
      - "3000:3000"
    stop_grace_period: 1s
    user: "1000:1000"
    command: >
      sh -c "
      echo 'Starting Docusaurus server...' &&
      npm install &&
      npm run clear &&
      npm run start -- --host 0.0.0.0
      "
