// SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
// SPDX-License-Identifier: BSD-3-Clause-Open-MPI

module.exports = {
  userDocsSidebar: [
    {
      type: 'category',
      label: 'User Documentation',
      collapsible: false,
      link: { type: 'doc', id: 'user_manual/index' },
      items: [
        {
          type: 'category',
          label: 'User Manual',
          collapsible: true,
          collapsed: false,
          items: [
            { type: 'autogenerated', dirName: 'user_manual/installation' },
            { type: 'autogenerated', dirName: 'user_manual/running' },
            { type: 'autogenerated', dirName: 'user_manual/config_reference' },
            { type: 'autogenerated', dirName: 'user_manual/outputs' },
            { type: 'autogenerated', dirName: 'user_manual/grafana' },
            { type: 'autogenerated', dirName: 'user_manual/troubleshooting' },
          ],
        },
        {
          type: 'category',
          label: 'Tutorials',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'tutorials/index' },
          items: [
            { type: 'autogenerated', dirName: 'tutorials/srsue' },
            { type: 'autogenerated', dirName: 'tutorials/cots_ue' },
            { type: 'autogenerated', dirName: 'tutorials/amari_ue' },
            { type: 'autogenerated', dirName: 'tutorials/handover' },
            { type: 'autogenerated', dirName: 'tutorials/oranru' },
            { type: 'autogenerated', dirName: 'tutorials/near-rt-ric' },
            { type: 'autogenerated', dirName: 'tutorials/ntn' },
            { type: 'autogenerated', dirName: 'tutorials/testmode' },
            { type: 'autogenerated', dirName: 'tutorials/dpdk' },
            { type: 'autogenerated', dirName: 'tutorials/matlab' },
            { type: 'autogenerated', dirName: 'tutorials/tuning' },
            { type: 'autogenerated', dirName: 'tutorials/k8s' },
            { type: 'autogenerated', dirName: 'tutorials/cu_du_split' },
          ],
        },
        {
          type: 'category',
          label: 'Integrations',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'integrations/index' },
          items: [
            {
              type: 'category',
              label: 'ORAN Radio Units',
              collapsed: true,
              items: [
                'integrations/radio_units/benetel',
                'integrations/radio_units/foxconn',
                'integrations/radio_units/liteon',
                'integrations/radio_units/picocom',
                'integrations/radio_units/vvdn',
              ],
            },
            {
              type: 'category',
              label: '5G Cores',
              collapsed: true,
              items: [
                'integrations/5g_cores/ella_core/index',
              ],
            },
            {
              type: 'category',
              label: 'Switches and Timing',
              collapsed: true,
              items: [
                'integrations/switches_and_timing/falcon',
                'integrations/switches_and_timing/meinberg',
                'integrations/switches_and_timing/mikrotik',
                'integrations/switches_and_timing/netgear',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Releases & Roadmap',
          collapsible: true,
          collapsed: true,
          link: { type: 'doc', id: 'releases/index' },
          items: [],
        },
      ],
    },
  ],

  knowledgeBaseSidebar: [
    {
      type: 'category',
      label: 'Knowledge Base',
      collapsible: false,
      link: { type: 'doc', id: 'knowledge_base/index' },
      items: [
        { type: 'autogenerated', dirName: 'knowledge_base/oran_gnb' },
        { type: 'autogenerated', dirName: 'knowledge_base/gnb_components' },
        { type: 'autogenerated', dirName: 'knowledge_base/gnb_interfaces' },
        { type: 'autogenerated', dirName: 'knowledge_base/cots_ues' },
      ],
    },
  ],

  devSidebar: [
    {
      type: 'category',
      label: 'Developer Zone',
      collapsible: false,
      link: { type: 'doc', id: 'dev_guide/index' },
      items: [
        {
          type: 'category',
          label: 'Software Architecture Guide',
          link: { type: 'doc', id: 'dev_guide/architecture_guide/index' },
          collapsed: true,
          items: [
            'dev_guide/architecture_guide/vision_and_goals',
            {
              type: 'category',
              label: 'Design Principles',
              link: { type: 'doc', id: 'dev_guide/architecture_guide/principles/index' },
              collapsed: true,
              items: [
                'dev_guide/architecture_guide/principles/clean_architecture',
                'dev_guide/architecture_guide/principles/solid',
                'dev_guide/architecture_guide/principles/oop',
              ],
            },
            {
              type: 'category',
              label: 'Realization',
              link: { type: 'doc', id: 'dev_guide/architecture_guide/realization/index' },
              collapsed: true,
              items: [
                'dev_guide/architecture_guide/realization/threading_model',
                'dev_guide/architecture_guide/realization/async_programming',
                'dev_guide/architecture_guide/realization/interfaces',
                'dev_guide/architecture_guide/realization/metrics',
                'dev_guide/architecture_guide/realization/realtime_safety',
                'dev_guide/architecture_guide/realization/cpp_language',
                'dev_guide/architecture_guide/realization/testing',
                {
                  type: 'category',
                  label: 'Plugins',
                  link: { type: 'doc', id: 'dev_guide/architecture_guide/realization/plugins/index' },
                  collapsed: true,
                  items: [
                    'dev_guide/architecture_guide/realization/plugins/phy_tap_interface',
                    'dev_guide/architecture_guide/realization/plugins/implementing',
                    'dev_guide/architecture_guide/realization/plugins/decorator_chaining',
                    'dev_guide/architecture_guide/realization/plugins/configuration',
                    'dev_guide/architecture_guide/realization/plugins/build_system',
                  ],
                },
                'dev_guide/architecture_guide/realization/design_patterns',
              ],
            },
            'dev_guide/architecture_guide/references',
          ],
        },
        {
          type: 'category',
          label: 'C++ Code Guide',
          link: { type: 'doc', id: 'dev_guide/code_guide/index' },
          collapsed: true,
          items: [
            'dev_guide/code_guide/language_libraries',
            'dev_guide/code_guide/mechanical_source_aspects',
            'dev_guide/code_guide/style_aspects_high_level',
            'dev_guide/code_guide/style_aspects_low_level',
            'dev_guide/code_guide/recommendations',
            'dev_guide/code_guide/self_generating_docs',
            'dev_guide/code_guide/commit_formatting',
          ],
        },
        'dev_guide/logging_guide/index',
        'dev_guide/testing_policy/index',
        'dev_guide/contributing_guide/index',
        'dev_guide/reporting/index',
        {
          type: 'link',
          label: 'Doxygen',
          href: 'pathname:///doxygen/index.html',
        },
      ],
    },
  ],

  communitySidebar: [],

  qaSidebar: [],
};
