module.exports = {
    docsSidebar: [
        { type: 'autogenerated', dirName: '.' },
        {
            type: 'link',
            label: 'Doxygen',
            href: 'pathname:///doxygen/index.html',
        },
    ],
};
