// SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
// SPDX-License-Identifier: BSD-3-Clause-Open-MPI

module.exports = {
    docsSidebar: [
        { type: 'autogenerated', dirName: '.' },
        {
            type: 'link',
            label: 'Doxygen',
            href: 'pathname:///doxygen/index.html',
        },
    ],
};
