uicc0 = {
  imsi = "001010123456780";
  key = "00112233445566778899aabbccddeeff";
  opc= "63bfa50ee6523365ff14c1f45f88737d";
  pdu_sessions = ({ dnn = "internet"; 
                    nssai_sst = 1; 
                    });
}


thread-pool = "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1"

r               = 51;
numerology      = 1;
band            = 78;
C               = 3489420000;
ue-scan-carrier = 1;
E               = 1;
uecap_file      = "../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/uecap_ports1.xml";

device = {
  name = "oai_zmqdevif";
};

zmq = (
  {
    tx_channels = ( "tcp://127.0.0.1:4557" );
    rx_channels = ( "tcp://127.0.0.1:4556" );
  }
);
